### ISSUE TITLE
Fatal error on WebDriver (Selenium)

### ISSUE THREAD

**Issue by vermaxik** [tldev-de/immopushr#4]
Hi Tobi,

thanks a lot for great library.  I didn't have a lot of experience with PHP last time, but extended and used your script and running it locally via docker-compose every hour.  

The cron script executes the first time successfully, but on the second attempt (in 1 hour)  it raises error:

```bash
Fatal error: Uncaught Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"capabilities":{"firstMatch":[{"browserName":"chrome","goog:chromeOptions":{"args":["--window-size=1920,1080","--lang=de-DE","--no-sandbox","--start-maximized","--disable-infobars","--disable-gpu","--disable-blink-features=AutomationControlled","--user-agent=Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/88.0.4324.150 Safari\/537.36"]}}]},"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"args":["--window-size=1920,1080","--lang=de-DE","--no-sandbox","--start-maximized","--disable-infobars","--disable-gpu","--disable-blink-features=AutomationControlled","--user-agent=Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/88.0.4324.150 Safari\/537.36"]}}}
```

```
Operation timed out after 30002 milliseconds with 0 bytes received in /app/vendor/php-webdriver/webdriver/lib/Remote/HttpCommandExecutor.php:332
```

After restarting container, it works only 1 time and the error appears again.

Do you know how to fix this issue? Thank you.

**Comment by tldev-de** [comment]
Hi vermaxik,

nice to hear that you found the project.

Did I understand correctly, that you modified the script? The behaviour, you're describing, occurs when you're not closing the selenium connection. Have a look at the [selenium documentation](https://github.com/SeleniumHQ/docker-selenium#debugging) - you can use VNC to connect to the selenium container. Be sure that the browser is closed after the first run.

If you think, your modifications might be helpful for others, don't hesitate to create a merge request. I would love to see community contributions :)

**Comment by vermaxik** [comment]
Thanks for answer, I'll try it :+1:  it's quite dirty changes and visual message changes, not sure if it will be useful for others. I'll close this issue for now.
